name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    
    name: "Build&Test&Deploy: node-${{ matrix.node_version }}"
    steps:
    - uses: actions/checkout@v2
    - name: Set node version to ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install deps
      run: npm install
    - name: Build
      run: npm run build
    - name: Run unit tests
      run: npm run test 
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: main
        folder: dist
        ssh-key: ${{ secrets.GH_PAGE_SECRET }}
        repository-name: NCU-Plus/ncu-plus.github.io
